# Form implementation generated from reading ui file 'finaleffort.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(270, 80, 191, 61))
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")

        self.widget_main = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_main.setEnabled(True)
        self.widget_main.setGeometry(QtCore.QRect(270, 160, 181, 301))
        self.widget_main.setObjectName("widget_main")

        self.BreakTimeEntry_2 = QtWidgets.QLineEdit(parent=self.widget_main)
        self.BreakTimeEntry_2.setGeometry(QtCore.QRect(20, 150, 141, 20))
        self.BreakTimeEntry_2.setObjectName("BreakTimeEntry_2")
        self.label_2_2 = QtWidgets.QLabel(parent=self.widget_main)
        self.label_2_2.setEnabled(True)
        self.label_2_2.setGeometry(QtCore.QRect(20, 20, 111, 31))
        self.label_2_2.setObjectName("label_2_2")
        self.label_3_2 = QtWidgets.QLabel(parent=self.widget_main)
        self.label_3_2.setGeometry(QtCore.QRect(20, 80, 111, 21))
        self.label_3_2.setObjectName("label_3_2")
        self.labelInfo_2 = QtWidgets.QLabel(parent=self.widget_main)
        self.labelInfo_2.setGeometry(QtCore.QRect(20, 250, 141, 16))
        self.labelInfo_2.setText("")
        self.labelInfo_2.setObjectName("labelInfo_2")
        self.StartTimeEntry_2 = QtWidgets.QLineEdit(parent=self.widget_main)
        self.StartTimeEntry_2.setGeometry(QtCore.QRect(20, 50, 141, 20))
        self.StartTimeEntry_2.setObjectName("StartTimeEntry_2")
        self.EndTimeEntry_2 = QtWidgets.QLineEdit(parent=self.widget_main)
        self.EndTimeEntry_2.setGeometry(QtCore.QRect(20, 100, 141, 20))
        self.EndTimeEntry_2.setObjectName("EndTimeEntry_2")
        self.SubmitButton_2 = QtWidgets.QPushButton(parent=self.widget_main)
        self.SubmitButton_2.setGeometry(QtCore.QRect(20, 200, 111, 31))
        self.SubmitButton_2.setObjectName("SubmitButton_2")
        self.label_4_2 = QtWidgets.QLabel(parent=self.widget_main)
        self.label_4_2.setGeometry(QtCore.QRect(20, 130, 111, 21))
        self.label_4_2.setObjectName("label_4_2")
        self.ReenterButton_2 = QtWidgets.QPushButton(parent=self.widget_main)
        self.ReenterButton_2.setGeometry(QtCore.QRect(130, 200, 31, 31))
        self.ReenterButton_2.setObjectName("ReenterButton_2")

        self.widget_second = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_second.setEnabled(False)
        self.widget_second.setGeometry(QtCore.QRect(270, 150, 381, 311))
        self.widget_second.setObjectName("widget_second")

        self.SignUpButton_1 = QtWidgets.QPushButton(parent=self.widget_second)
        self.SignUpButton_1.setGeometry(QtCore.QRect(90, 210, 71, 31))
        self.SignUpButton_1.setObjectName("SignUpButton_1")
        self.UsernameEntry_1 = QtWidgets.QLineEdit(parent=self.widget_second)
        self.UsernameEntry_1.setGeometry(QtCore.QRect(20, 60, 141, 20))
        self.UsernameEntry_1.setObjectName("UsernameEntry_1")
        self.label_1 = QtWidgets.QLabel(parent=self.widget_second)
        self.label_1.setEnabled(False)
        self.label_1.setGeometry(QtCore.QRect(20, 30, 111, 31))
        self.label_1.setObjectName("label_1")
        self.PasswordEntry_1 = QtWidgets.QLineEdit(parent=self.widget_second)
        self.PasswordEntry_1.setGeometry(QtCore.QRect(20, 110, 141, 20))
        self.PasswordEntry_1.setObjectName("PasswordEntry_1")
        self.LoginButton_1 = QtWidgets.QPushButton(parent=self.widget_second)
        self.LoginButton_1.setGeometry(QtCore.QRect(20, 210, 71, 31))
        self.LoginButton_1.setObjectName("LoginButton_1")
        self.labelInfo_3 = QtWidgets.QLabel(parent=self.widget_second)
        self.labelInfo_3.setGeometry(QtCore.QRect(20, 260, 141, 16))
        self.labelInfo_3.setText("")
        self.labelInfo_3.setObjectName("labelInfo_3")
        self.Plabel_1 = QtWidgets.QLabel(parent=self.widget_second)
        self.Plabel_1.setGeometry(QtCore.QRect(20, 90, 111, 21))
        self.Plabel_1.setObjectName("Plabel_1")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">Time Clock App</span></p></body></html>"))
        self.label_2_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Started Work</span></p></body></html>"))
        self.label_3_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Ended Work</span></p></body></html>"))
        self.SubmitButton_2.setText(_translate("MainWindow", "Login"))
        self.label_4_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Break</span></p></body></html>"))
        self.ReenterButton_2.setText(_translate("MainWindow", "R"))
        self.SignUpButton_1.setText(_translate("MainWindow", "Sign Up"))
        self.label_1.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Username</span></p></body></html>"))
        self.LoginButton_1.setText(_translate("MainWindow", "Login"))
        self.Plabel_1.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Password</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
